project_id = "nexozjpjbhqfjplrogvz"

[functions.pawapay-deposit]
verify_jwt = false

[functions.pawapay-status]
verify_jwt = false

[functions.pawapay-webhook]
verify_jwt = false

[functions.stripe-create-payment-intent]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.get-stripe-config]
verify_jwt = false

[functions.release-pending-funds]
verify_jwt = false

[functions.rewrite-description]
verify_jwt = false

[functions.send-campaign]
verify_jwt = false

[functions.notify-sale]
verify_jwt = false

[functions.analyze-kyc]
verify_jwt = false

[functions.admin-kyc]
verify_jwt = false

[functions.marketplace-search]
verify_jwt = false

[functions.visual-search]
verify_jwt = false

[functions.analyze-badge-eligibility]
verify_jwt = false

[functions.subscribe-badge]
verify_jwt = false

[functions.admin-badge]
verify_jwt = false

[functions.community-access]
verify_jwt = false

[functions.didit-webhook]
verify_jwt = false

[functions.track-visit]
enabled = true
verify_jwt = false
import_map = "./functions/track-visit/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/track-visit/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/track-visit/*.html" ]
